pipeline {
    agent any
    
    tools {
        terraform 'terraform-12'
    }
    stages {
        stage ("checkout from GIT") {
            steps {
                git branch: 'main',  url: 'https://github.com/sk4evercache/my.git'
            }
        }
        stage ("terraform init") {
            steps {
                sh '''
                   cd /var/lib/jenkins/workspace/po/aws-instance-first-script
                   terraform init
                '''
            }
        }
      
        }
       
      
        stage ("terraform apply") {
            steps {
                 sh '''
                   cd /var/lib/jenkins/workspace/po/aws-instance-first-script
                   terraform apply -auto-approve
                '''
            }
        }
    }
}
